// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of useLM
//        bit 31~0 - useLM[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of useLN
//        bit 31~0 - useLN[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of useLP
//        bit 31~0 - useLP[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMUL_MATRIX_AXILITES_ADDR_USELM_DATA 0x10
#define XMUL_MATRIX_AXILITES_BITS_USELM_DATA 32
#define XMUL_MATRIX_AXILITES_ADDR_USELN_DATA 0x18
#define XMUL_MATRIX_AXILITES_BITS_USELN_DATA 32
#define XMUL_MATRIX_AXILITES_ADDR_USELP_DATA 0x20
#define XMUL_MATRIX_AXILITES_BITS_USELP_DATA 32

