# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\SoC_2022_MJU\HW2_2\HW2_2_vivado\HW2_2_vivado.srcs\sources_1\bd\design_1\ui\bd_1f5defd0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


