# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SEP16/SoC_2022_MJU/HW2_2/HW2_2_vivado/HW2_2_vivado.srcs/sources_1/bd/design_1/ip/design_1_matrixmul_0_0/design_1_matrixmul_0_0.xci
# IP: The module: 'design_1_matrixmul_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SEP16/SoC_2022_MJU/HW2_2/HW2_2_vivado/HW2_2_vivado.srcs/sources_1/bd/design_1/ip/design_1_matrixmul_0_0/constraints/matrixmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_matrixmul_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/SEP16/SoC_2022_MJU/HW2_2/HW2_2_vivado/HW2_2_vivado.srcs/sources_1/bd/design_1/ip/design_1_matrixmul_0_0/design_1_matrixmul_0_0.xci
# IP: The module: 'design_1_matrixmul_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SEP16/SoC_2022_MJU/HW2_2/HW2_2_vivado/HW2_2_vivado.srcs/sources_1/bd/design_1/ip/design_1_matrixmul_0_0/constraints/matrixmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_matrixmul_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
