// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmul_matrix.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMul_matrix_CfgInitialize(XMul_matrix *InstancePtr, XMul_matrix_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMul_matrix_Set_useLM(XMul_matrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMul_matrix_WriteReg(InstancePtr->Axilites_BaseAddress, XMUL_MATRIX_AXILITES_ADDR_USELM_DATA, Data);
}

u32 XMul_matrix_Get_useLM(XMul_matrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMul_matrix_ReadReg(InstancePtr->Axilites_BaseAddress, XMUL_MATRIX_AXILITES_ADDR_USELM_DATA);
    return Data;
}

void XMul_matrix_Set_useLN(XMul_matrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMul_matrix_WriteReg(InstancePtr->Axilites_BaseAddress, XMUL_MATRIX_AXILITES_ADDR_USELN_DATA, Data);
}

u32 XMul_matrix_Get_useLN(XMul_matrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMul_matrix_ReadReg(InstancePtr->Axilites_BaseAddress, XMUL_MATRIX_AXILITES_ADDR_USELN_DATA);
    return Data;
}

void XMul_matrix_Set_useLP(XMul_matrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMul_matrix_WriteReg(InstancePtr->Axilites_BaseAddress, XMUL_MATRIX_AXILITES_ADDR_USELP_DATA, Data);
}

u32 XMul_matrix_Get_useLP(XMul_matrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMul_matrix_ReadReg(InstancePtr->Axilites_BaseAddress, XMUL_MATRIX_AXILITES_ADDR_USELP_DATA);
    return Data;
}

