set_property SRC_FILE_INFO {cfile:C:/Users/SEP16/SoC_2022_MJU/Lab1-PL/Lab1-PL.srcs/constrs_1/new/nand_const.xdc rfile:../../../Lab1-PL.srcs/constrs_1/new/nand_const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports A]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports B]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports X]
