// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrixmul_1D_HH_
#define _matrixmul_1D_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "matrixmul_1D_mac_bkb.h"
#include "matrixmul_1D_Input.h"
#include "matrixmul_1D_A.h"
#include "matrixmul_1D_AB_2D.h"

namespace ap_rtl {

struct matrixmul_1D : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<15> > Input_orign_address0;
    sc_out< sc_logic > Input_orign_ce0;
    sc_in< sc_lv<8> > Input_orign_q0;
    sc_out< sc_lv<14> > AB_address0;
    sc_out< sc_logic > AB_ce0;
    sc_out< sc_logic > AB_we0;
    sc_out< sc_lv<32> > AB_d0;


    // Module declarations
    matrixmul_1D(sc_module_name name);
    SC_HAS_PROCESS(matrixmul_1D);

    ~matrixmul_1D();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    matrixmul_1D_Input* Input_U;
    matrixmul_1D_A* A_U;
    matrixmul_1D_A* B_U;
    matrixmul_1D_AB_2D* AB_2D_U;
    matrixmul_1D_mac_bkb<1,1,8,8,19,19>* matrixmul_1D_mac_bkb_U1;
    sc_signal< sc_lv<18> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<9> > i_fu_345_p2;
    sc_signal< sc_lv<9> > i_reg_678;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<17> > tmp_2_cast_fu_359_p1;
    sc_signal< sc_lv<17> > tmp_2_cast_reg_683;
    sc_signal< sc_lv<1> > exitcond7_fu_339_p2;
    sc_signal< sc_lv<8> > j_1_fu_369_p2;
    sc_signal< sc_lv<8> > j_1_reg_691;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond6_fu_363_p2;
    sc_signal< sc_lv<17> > tmp_3_fu_396_p2;
    sc_signal< sc_lv<17> > tmp_3_reg_701;
    sc_signal< sc_lv<2> > i_1_fu_411_p2;
    sc_signal< sc_lv<2> > i_1_reg_709;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<2> > j_2_fu_423_p2;
    sc_signal< sc_lv<2> > j_2_reg_717;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > tmp_8_fu_439_p1;
    sc_signal< sc_lv<64> > tmp_8_reg_722;
    sc_signal< sc_lv<1> > exitcond4_fu_417_p2;
    sc_signal< sc_lv<2> > i_2_fu_450_p2;
    sc_signal< sc_lv<2> > i_2_reg_735;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<2> > j_3_fu_462_p2;
    sc_signal< sc_lv<2> > j_3_reg_743;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<1> > exitcond2_fu_456_p2;
    sc_signal< sc_lv<4> > i_3_fu_506_p2;
    sc_signal< sc_lv<4> > i_3_reg_756;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<4> > j_5_fu_518_p2;
    sc_signal< sc_lv<4> > j_5_reg_764;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<14> > AB_2D_addr_reg_769;
    sc_signal< sc_lv<1> > exitcond9_fu_512_p2;
    sc_signal< sc_lv<4> > k_1_fu_545_p2;
    sc_signal< sc_lv<4> > k_1_reg_777;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<1> > exitcond10_fu_539_p2;
    sc_signal< sc_lv<8> > A_q0;
    sc_signal< sc_lv<8> > A_load_reg_792;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<8> > B_q0;
    sc_signal< sc_lv<8> > B_load_reg_797;
    sc_signal< sc_lv<19> > grp_fu_667_p3;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<8> > i_4_fu_593_p2;
    sc_signal< sc_lv<8> > i_4_reg_810;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<16> > tmp_19_cast1_fu_607_p1;
    sc_signal< sc_lv<16> > tmp_19_cast1_reg_815;
    sc_signal< sc_lv<1> > exitcond1_fu_587_p2;
    sc_signal< sc_lv<14> > tmp_s_fu_615_p3;
    sc_signal< sc_lv<14> > tmp_s_reg_820;
    sc_signal< sc_lv<8> > j_4_fu_633_p2;
    sc_signal< sc_lv<8> > j_4_reg_828;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<1> > exitcond_fu_627_p2;
    sc_signal< sc_lv<14> > tmp_14_fu_653_p2;
    sc_signal< sc_lv<14> > tmp_14_reg_838;
    sc_signal< sc_lv<15> > Input_address0;
    sc_signal< sc_logic > Input_ce0;
    sc_signal< sc_logic > Input_we0;
    sc_signal< sc_lv<8> > Input_q0;
    sc_signal< sc_lv<14> > A_address0;
    sc_signal< sc_logic > A_ce0;
    sc_signal< sc_logic > A_we0;
    sc_signal< sc_lv<14> > B_address0;
    sc_signal< sc_logic > B_ce0;
    sc_signal< sc_logic > B_we0;
    sc_signal< sc_lv<14> > AB_2D_address0;
    sc_signal< sc_logic > AB_2D_ce0;
    sc_signal< sc_logic > AB_2D_we0;
    sc_signal< sc_lv<19> > AB_2D_q0;
    sc_signal< sc_lv<9> > i3_reg_199;
    sc_signal< sc_lv<8> > j_reg_211;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<2> > i4_reg_222;
    sc_signal< sc_lv<2> > j5_reg_234;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > exitcond5_fu_405_p2;
    sc_signal< sc_lv<2> > i6_reg_245;
    sc_signal< sc_lv<2> > j7_reg_257;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > exitcond3_fu_444_p2;
    sc_signal< sc_lv<4> > i8_reg_269;
    sc_signal< sc_lv<4> > j9_reg_281;
    sc_signal< sc_lv<1> > exitcond8_fu_500_p2;
    sc_signal< sc_lv<4> > k_reg_293;
    sc_signal< sc_lv<19> > sum_reg_304;
    sc_signal< sc_lv<8> > i5_reg_317;
    sc_signal< sc_lv<8> > j4_reg_328;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<64> > tmp_5_fu_387_p1;
    sc_signal< sc_lv<64> > tmp_3_cast_fu_401_p1;
    sc_signal< sc_lv<64> > tmp_2_fu_480_p1;
    sc_signal< sc_lv<64> > tmp_10_fu_495_p1;
    sc_signal< sc_lv<64> > tmp_17_fu_534_p1;
    sc_signal< sc_lv<64> > tmp_20_fu_561_p1;
    sc_signal< sc_lv<64> > tmp_22_fu_576_p1;
    sc_signal< sc_lv<64> > tmp_23_cast_fu_648_p1;
    sc_signal< sc_lv<64> > tmp_15_fu_663_p1;
    sc_signal< sc_lv<16> > tmp_1_fu_351_p3;
    sc_signal< sc_lv<8> > tmp_fu_375_p1;
    sc_signal< sc_lv<16> > tmp_4_fu_379_p3;
    sc_signal< sc_lv<17> > tmp_6_cast_fu_392_p1;
    sc_signal< sc_lv<9> > tmp_7_fu_429_p4;
    sc_signal< sc_lv<15> > tmp_9_fu_468_p5;
    sc_signal< sc_lv<9> > tmp_6_fu_485_p4;
    sc_signal< sc_lv<11> > tmp_13_fu_524_p4;
    sc_signal< sc_lv<11> > tmp_19_fu_551_p4;
    sc_signal< sc_lv<11> > tmp_21_fu_566_p4;
    sc_signal< sc_lv<15> > tmp_11_fu_599_p3;
    sc_signal< sc_lv<7> > tmp_12_fu_611_p1;
    sc_signal< sc_lv<16> > tmp_12_cast_fu_639_p1;
    sc_signal< sc_lv<16> > tmp_18_fu_643_p2;
    sc_signal< sc_lv<14> > j4_cast2_fu_623_p1;
    sc_signal< sc_lv<8> > grp_fu_667_p0;
    sc_signal< sc_lv<8> > grp_fu_667_p1;
    sc_signal< sc_lv<18> > ap_NS_fsm;
    sc_signal< sc_lv<16> > grp_fu_667_p00;
    sc_signal< sc_lv<16> > grp_fu_667_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<18> ap_ST_fsm_state1;
    static const sc_lv<18> ap_ST_fsm_state2;
    static const sc_lv<18> ap_ST_fsm_state3;
    static const sc_lv<18> ap_ST_fsm_state4;
    static const sc_lv<18> ap_ST_fsm_state5;
    static const sc_lv<18> ap_ST_fsm_state6;
    static const sc_lv<18> ap_ST_fsm_state7;
    static const sc_lv<18> ap_ST_fsm_state8;
    static const sc_lv<18> ap_ST_fsm_state9;
    static const sc_lv<18> ap_ST_fsm_state10;
    static const sc_lv<18> ap_ST_fsm_state11;
    static const sc_lv<18> ap_ST_fsm_state12;
    static const sc_lv<18> ap_ST_fsm_state13;
    static const sc_lv<18> ap_ST_fsm_state14;
    static const sc_lv<18> ap_ST_fsm_state15;
    static const sc_lv<18> ap_ST_fsm_state16;
    static const sc_lv<18> ap_ST_fsm_state17;
    static const sc_lv<18> ap_ST_fsm_state18;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<19> ap_const_lv19_0;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<9> ap_const_lv9_100;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<8> ap_const_lv8_80;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_AB_2D_address0();
    void thread_AB_2D_ce0();
    void thread_AB_2D_we0();
    void thread_AB_address0();
    void thread_AB_ce0();
    void thread_AB_d0();
    void thread_AB_we0();
    void thread_A_address0();
    void thread_A_ce0();
    void thread_A_we0();
    void thread_B_address0();
    void thread_B_ce0();
    void thread_B_we0();
    void thread_Input_address0();
    void thread_Input_ce0();
    void thread_Input_orign_address0();
    void thread_Input_orign_ce0();
    void thread_Input_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond10_fu_539_p2();
    void thread_exitcond1_fu_587_p2();
    void thread_exitcond2_fu_456_p2();
    void thread_exitcond3_fu_444_p2();
    void thread_exitcond4_fu_417_p2();
    void thread_exitcond5_fu_405_p2();
    void thread_exitcond6_fu_363_p2();
    void thread_exitcond7_fu_339_p2();
    void thread_exitcond8_fu_500_p2();
    void thread_exitcond9_fu_512_p2();
    void thread_exitcond_fu_627_p2();
    void thread_grp_fu_667_p0();
    void thread_grp_fu_667_p00();
    void thread_grp_fu_667_p1();
    void thread_grp_fu_667_p10();
    void thread_i_1_fu_411_p2();
    void thread_i_2_fu_450_p2();
    void thread_i_3_fu_506_p2();
    void thread_i_4_fu_593_p2();
    void thread_i_fu_345_p2();
    void thread_j4_cast2_fu_623_p1();
    void thread_j_1_fu_369_p2();
    void thread_j_2_fu_423_p2();
    void thread_j_3_fu_462_p2();
    void thread_j_4_fu_633_p2();
    void thread_j_5_fu_518_p2();
    void thread_k_1_fu_545_p2();
    void thread_tmp_10_fu_495_p1();
    void thread_tmp_11_fu_599_p3();
    void thread_tmp_12_cast_fu_639_p1();
    void thread_tmp_12_fu_611_p1();
    void thread_tmp_13_fu_524_p4();
    void thread_tmp_14_fu_653_p2();
    void thread_tmp_15_fu_663_p1();
    void thread_tmp_17_fu_534_p1();
    void thread_tmp_18_fu_643_p2();
    void thread_tmp_19_cast1_fu_607_p1();
    void thread_tmp_19_fu_551_p4();
    void thread_tmp_1_fu_351_p3();
    void thread_tmp_20_fu_561_p1();
    void thread_tmp_21_fu_566_p4();
    void thread_tmp_22_fu_576_p1();
    void thread_tmp_23_cast_fu_648_p1();
    void thread_tmp_2_cast_fu_359_p1();
    void thread_tmp_2_fu_480_p1();
    void thread_tmp_3_cast_fu_401_p1();
    void thread_tmp_3_fu_396_p2();
    void thread_tmp_4_fu_379_p3();
    void thread_tmp_5_fu_387_p1();
    void thread_tmp_6_cast_fu_392_p1();
    void thread_tmp_6_fu_485_p4();
    void thread_tmp_7_fu_429_p4();
    void thread_tmp_8_fu_439_p1();
    void thread_tmp_9_fu_468_p5();
    void thread_tmp_fu_375_p1();
    void thread_tmp_s_fu_615_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
